version: '2'
services:
  webapp:
    image: amsdard.io/krzysztof.kabala/symfony-demo-webapp:1.0
    stdin_open: true
    tty: true
    links:
    - mysql:mysql
    - redis:redis
    labels:
      traefik.enable: 'true'
      traefik.domain: app.amsdard.io
      io.rancher.container.pull_image: always
      traefik.alias: symfony-demo-webapp
  mysql:
    image: mariadb:10
    stdin_open: true
    volumes:
    - krzysztof.kabala-mysql-var-lib-mysql:/var/lib/mysql
    tty: true
  redis:
    image: redis:4-alpine
    stdin_open: true
    tty: true